### ISSUE TITLE
AUTOFIRMA client not launching

### ISSUE THREAD

**Issue by aguamemnon** [keensoft/alfresco-esign-cert#18]
with alfresco 5.1 comunity , esign-cert 1.3.1 , i have no error in log alfresco and share , no error in catalina log, but the client show the logo and that's all , with the java console , just this warning : WARNING: Error en la validacion de los certificados contra el almacen de Java: java.io.EOFException

http://pastebin.com/VRDriz31

**Comment by angelborroy-ks** [comment]
Which browser and client OS are you using?

**Comment by aguamemnon** [comment]
hi , and happy new year ;)

i have test on firefox 50 / IE 11  

on chrome it's ok

**Comment by angelborroy-ks** [comment]
It looks like you have not accepted to include the certificate included in the Applet into your CA Store.

On Chrome is launching local app, so no CA validation is performed.

**Comment by aguamemnon** [comment]
i have include 3 cert from applet 2 comodo 1 keensoft  , i dont think it s the problem

**Comment by aguamemnon** [comment]
if you want i can give you a teamveiwer control to check my pc and check alfresco server.
