### ISSUE TITLE
Review copying process

### ISSUE THREAD

**Issue by angelborroy-ks** [keensoft/alfresco-esign-cert#26]
Following workaround has been provided when copying signed documents:

```
if (document.hasAspect("sign:signed")) {
	
	var dstFolderName = "...";

	var newDoc = document.copy(dstFolder, true);

	// Required to remove signature association from copied node
	// to avoid loose association from original node
	// when copied node is deleted
	var signatureAssoc = newDoc.assocs["sign:signatureAssoc"];
	for (var i = 0, len = signatureAssoc.length; i < len; i++) {
		newDoc.removeAssociation(signatureAssoc[i],"sign:signatureAssoc");
	}
	
	newDoc.save();
	
}
```

This behaviour requires further investigation.

**Comment by tsiakmaki** [comment]
Just noticed that when we copy a signed document, the system creates more the associated signatures. If the creator user is a different from the signer, it adds associated signatures for the creator as well. 
 
Where this workarround is ment to be added?

**Comment by angelborroy-ks** [comment]
You can use it as a rule when document is updated, as it is a repo JavaScript source. Probably some changes are required in the above sample. 

However we have to fix this "officially" by adding some new behaviour and release a version.

Let me see if I can release this version for the next week.

**Comment by tsiakmaki** [comment]
Made 2 small changes, and seems to work: 

1. CustomBehaviour.java - onCreateNode()
we replaced:
`if (nodeService.exists(node)) {`
with:
```
// if onCreateNode the document hasSignedAspect, the document is being copied inside alfresco
boolean hasSignedAspect = nodeService.hasAspect(node, SignModel.ASPECT_SIGNED);
if (nodeService.exists(node) && !hasSignedAspect) {
...
```

2. TransactionalDeleteBehaviour.java
check if node exists added: 
```
public Void execute() throws Throwable {
nodeService.deleteNode(nodeToBeReviewed);
if(nodeService.exists(nodeToBeReviewed)) {
nodeService.deleteNode(nodeToBeReviewed);
}
return null;
```

and seems to work.

**Comment by angelborroy-ks** [comment]
Can you be so kind to issue a pull request for me?

I'll make some tests on this, package a new release and I'll credit your contribution (of course!) when all works properly.

Thanks.
