### ISSUE TITLE
Applet not loading on Firefox (Windows and Linux)

### ISSUE THREAD

**Issue by mikelasla** [keensoft/alfresco-esign-cert#27]
Tested with

Firefox 51.0.1 on windows 10
Firefox 45.6.0 on Debian 9

[Step to reproduce]

Execute the signature action

[Expected result]

applet is loaded

[Actual result]

Autofirma desktop application is loaded

[Additional notes]

* According to the Java console output, the MiniApplet.sign method is called before MiniApplet.cargarMiniApplet ends
* The MiniApplet.sign method checks if the MiniApplet is ready, if its not, calls the native application

**Comment by angelborroy-ks** [comment]
Won't fix
