### ISSUE TITLE
Problemas con Instalacion de esign-cert 

### ISSUE THREAD

**Issue by juliocdn** [keensoft/alfresco-esign-cert#29]
Buen dia con todos, tengo ubuntu server 16.04 con alfresco 5.2. Y bueno estoy intentando instalar el esign-cert como me indico Angel Borroy, pero no se en que ruta debo  copiar las carpetas esign-cert-repo y esign-cert-share del ubuntu server. 
Mi instalación de alfresco la tengo en la sgte ruta : /opt/alfresco/tomcat/shared/classes  

Luego hay que agregar las sgtes lineas en alfresco-properties 

# Native @firma parameters separated by tab (\t)
esign.cert.params.pades=signaturePage=1\tsignaturePositionOnPageLowerLeftX=120\tsignaturePositionOnPageLowerLeftY=50\tsignaturePositionOnPageUpperRightX=220\tsignaturePositionOnPageUpperRightY=150\t
esign.cert.params.cades=mode=explicit
# Signature algorithm: SHA1withRSA, SHA256withRSA, SHA384withRSA, SHA512withRSA
esign.cert.signature.alg=SHA512withRSA
esign.cert.params.firstSignaturePosition=signaturePage={page}\tsignaturePositionOnPageLowerLeftX=50\tsignaturePositionOnPageLowerLeftY=45\tsignaturePositionOnPageUpperRightX=305\tsignaturePositionOnPageUpperRightY=69\t
esign.cert.params.secondSignaturePosition=signaturePage={page}\tsignaturePositionOnPageLowerLeftX=310\tsignaturePositionOnPageLowerLeftY=45\tsignaturePositionOnPageUpperRightX=565\tsignaturePositionOnPageUpperRightY=69\t
esign.cert.params.thirdSignaturePosition=signaturePage={page}\tsignaturePositionOnPageLowerLeftX=50\tsignaturePositionOnPageLowerLeftY=23\tsignaturePositionOnPageUpperRightX=305\tsignaturePositionOnPageUpperRightY=47\t
esign.cert.params.fourthSignaturePosition=signaturePage={page}\tsignaturePositionOnPageLowerLeftX=310\tsignaturePositionOnPageLowerLeftY=23\tsignaturePositionOnPageUpperRightX=565\tsignaturePositionOnPageUpperRightY=47\t
esign.cert.params.fifthSignaturePosition=signaturePage={page}\tsignaturePositionOnPageLowerLeftX=50\tsignaturePositionOnPageLowerLeftY=1\tsignaturePositionOnPageUpperRightX=305\tsignaturePositionOnPageUpperRightY=25\t
esign.cert.params.sixthSignaturePosition=signaturePage={page}\tsignaturePositionOnPageLowerLeftX=310\tsignaturePositionOnPageLowerLeftY=1\tsignaturePositionOnPageUpperRightX=565\tsignaturePositionOnPageUpperRightY=25\t

# Property for disable sign other docs
esign.cert.signOtherDocs=false

# Sign Purpose (Default enabled=false)
esign.cert.params.signPurpose.enabled=false

Les agradecería me puedan ayudar. 

Saludos.

**Comment by angelborroy-ks** [comment]
Cuando se suministran ficheros empaquetados AMP en Alfresco (https://github.com/keensoft/alfresco-esign-cert/releases) lo más cómodo es copiarlos a la carpeta `/opt/alfresco/amp` y `/opt/alfresco/amp_share` para después desplegarlos utilizando el ejecutable `/opt/alfresco/bin/apply_amps.sh`

Este es un mecanismo estándar que sirve para muchos _addons_ de Alfresco, no es una técnica específica de este _addon_.

**Comment by juliocdn** [comment]
Gracias Angel, ya puede instalar la opción firma como me indicaste lineas arriba, me aparece la opción firma en la interfaz gráfica de alfresco. Pero cuando le doy firmar me sale esto.

![image](https://cloud.githubusercontent.com/assets/16858347/25103598/ceaec65a-2382-11e7-8b31-cf13db28279b.png)

desaparece esta ventana y no firma nada. 

Hay que realizar alguna configuración mas.
Gracias de antemano

Atte.
Julio Delgado  (Perù)

**Comment by angelborroy-ks** [comment]
Cuando se utilizan applets en Firefox, hay que realizar una serie de operaciones para que puedan ser ejecutados. 

Puedes encontrar información en la propia página de Firefox: https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/How-to-allow-Java-on-trusted-sites/ta-p/6206

**Comment by juliocdn** [comment]
Buenas tardes Angel, acabo de instalar y configurar java en iexplore 11 como en tu video : https://www.youtube.com/watch?v=xHJ_fC73EwY  . y me sale estos pantallazoss pero no me sale para elegir el certificado :( .
Adjunto pantallazos de mi configuracion de java 8
![image](https://cloud.githubusercontent.com/assets/16858347/25144417/56962224-2433-11e7-865f-991b5c7f188f.png)
![image](https://cloud.githubusercontent.com/assets/16858347/25144419/59b276e2-2433-11e7-91ff-fd3fac4bde36.png)
![image](https://cloud.githubusercontent.com/assets/16858347/25144422/5c74207e-2433-11e7-862e-aa59e1f9b089.png)
![image](https://cloud.githubusercontent.com/assets/16858347/25144426/5fa31b38-2433-11e7-8218-6ee68fb5fdbb.png)
![image](https://cloud.githubusercontent.com/assets/16858347/25144430/61e75922-2433-11e7-9b87-9335effc9104.png)


Pero no me sale para escoger la firma, como en tu video, ya me falta poco, apoyame. Gracias Angel. Saludos.

**Comment by angelborroy-ks** [comment]
Lo tienes bien configurado, parece que no tienes ningún certificado instalado en tu equipo.
