### ISSUE TITLE
Error with File Actions after installing esign-cert 1.52

### ISSUE THREAD

**Issue by miquelp** [keensoft/alfresco-esign-cert#38]
I'm running Alfresco 5.1.e and after installing the esign-cert 1.52 version (or pretty much any other) via the AMP files, I see this error on the top of the page when loading any file:

![error_esign](https://user-images.githubusercontent.com/6978727/28261767-d90ab06e-6ae0-11e7-855a-6ec6ea68813f.jpg)

I'm new to Alfresco and I've never faced this issue before, so I'm pretty lost and don't know what to do. If I back up alfresco.war and share.war to get esign-cert AMPs uninstalled everything goes back to normal, but that's obviously not what I want.

Let me know if you need any further information about logging or my Alfresco installation.

Thanks in advance.

**Comment by angelborroy-ks** [comment]
I've made a simple test and it looks to work properly.

1. Fresh Alfresco 201605 installation
2. Stop Alfresco
3. Copy esign-cert-repo-1.5.2.amp to amps directory
4. Copy esign-cert-share-1.5.2.amp to amps_share directory
5. Run apply_amps.sh script
6. Start Alfresco

Have you missed any step or are you following a different path?

**Comment by miquelp** [comment]
That's exactly the only thing I did. It wasn't a fresh installation though. 

Just stopped Alfresco, moved the repo and share amps to said directories, runned apply_amps.sh script, and started Alfresco. Anyway I'll keep investigating to see if it's just about my Alfresco installation.

Thanks.

**Comment by miquelp** [comment]
Hi Angel,

Good news, I fixed the issue by reinstalling the AMP files, but this time I executed the **apply_amps.sh** script with the **-force** flag and the error didn't show up after restarting Alfresco. 

Now Alfresco works fine but when I click on the "Firmar PDF" it keeps stuck trying to initialize the signing component (as reported in #33). I guess it might be about my web browser not being able to start Autofirma. Do you have any clue what could be going wrong? 

Thanks!

**Comment by angelborroy-ks** [comment]
It shouldn't be required to use **-force** flag to deploy this module... In fact, I've made my test without using this option.

Which browser and OS are you using?

**Comment by miquelp** [comment]
I'm using Windows 10 and the issue occurred both in Firefox and Chrome.

**Comment by angelborroy-ks** [comment]
Is AutoFirma working using it in a standalone way? This is the most common use case and it's working fine (afaik).

**Comment by miquelp** [comment]
Yes, it is working properly when I launch AutoFirma on Windows 10. I can sign PDFs and everything works fine. It only doesn't work when I try to launch Autofirma it on Chrome or Firefox through the Firma PDF action.

**Comment by angelborroy-ks** [comment]
Just try to debug in Chrome with the Dev Console if the "afirma://..." URL is invoked or not when you click the action in Alfresco Share.

**Comment by miquelp** [comment]
This is the error I'm getting on the Dev Console when clicking on Firmar PDF: 

`Uncaught ReferenceError: Exception is not defined
    at throwException (VM397 miniapplet.js:977)
    at signOperation (VM397 miniapplet.js:813)
    at Object.sign (VM397 miniapplet.js:753)
    at Object.sign (VM397 miniapplet.js:396)
    at doSign (VM398 sign-frame.jsp?mimeType=pdf&paramsCades=mode=explicit&paramsPades=signaturePage=1	signaturePo…:27)
    at doSign (<anonymous>:138:40)`

**Comment by miquelp** [comment]
Debugged it with the Dev Console and I got this error: 

`Uncaught ReferenceError: Exception is not defined
    at throwException (miniapplet.js:977)
    at signOperation (miniapplet.js:813)
    at Object.sign (miniapplet.js:753)
    at Object.sign (miniapplet.js:396)
    at doSign (sign-frame.jsp:27)
    at doSign (<anonymous>:138:40)`

**Comment by angelborroy-ks** [comment]
I don't know which version are you using. It looks like this 977 line is empty at the current version: https://github.com/keensoft/alfresco-esign-cert/blob/master/esign-cert-share/src/main/amp/web/sign/miniapplet.js#L977

**Comment by miquelp** [comment]
I'm using the 1.5.2.1705091001 version as I can see inside the Admin Console of Alfresco. 

I've just reinstalled Firefox and AutoFirma (in this order) and now when I click the action in Firefox it is able to launch AutoFirma, yet it cannot find any certificate in my keystore. Autofirma is just saying: 

"No hay un certificado válido en su almacén. Compruebe las fechas de caducidad e instale un certifiado válido"

But as I see my keystore was valid until 2013 so that's probably what's causing this issue.

So it seems to work on Firefox, but on Chrome I'm still facing that same issue.

**Comment by miquelp** [comment]
UPDATE: Got a valid keystore and it's now working fine on Firefox. Still facing the same issue on Chrome.

**Comment by miquelp** [comment]
UPDATE: Got a new valid keystore and esign-cert is perfectly working on Firefox. On Chrome it's still producing the same error.

**Comment by miquelp** [comment]
I'm closing this issue since the main error disappeared in Firefox and Internet Explorer, after executing **./apply_amps.sh -force** and reinstalling Firefox and AutoFirma in this order. 

Still facing the same error on Chrome as reported a few comments above. I'll keep investigating what's wrong with my Chrome and may open a new issue about it later on.
