### ISSUE TITLE
nothing is showing on document.

### ISSUE THREAD

**Issue by monicakumari** [keensoft/alfresco-esign-cert#39]
Hi. I am using this add-on with alfresco 5.2.
I have deployed and installed amps in fresh vanila installation, added the properties in alfresco-global.properties and started alfresco.
uploaded a pdf document. and tried to sign it. but its no showing anything on the document. 
I am attaching screeshots.. don't know what else I have to do or why its not working.

**1. uploaded the file**
![screenshot from 2018-01-11 14-48-41](https://user-images.githubusercontent.com/26789477/34817790-f2b5ec60-f6de-11e7-8596-7953757d3f94.png)

**2. sign document**
![screenshot from 2018-01-11 14-48-54](https://user-images.githubusercontent.com/26789477/34817807-043efed6-f6df-11e7-8e34-2d2b50ddb700.png)

**3. showing popup. **
![screenshot from 2018-01-11 14-48-57](https://user-images.githubusercontent.com/26789477/34817835-18099020-f6df-11e7-86f0-767a28896760.png)

then this popup disappers. and got no exception, no error message. but got no sign on the document. 

kindly let me know, what I missed or why its not working. 
thanks in advance.

**Comment by angelborroy-ks** [comment]
What browser are you using?
Did you installed "AutoFirma" local program?

**Comment by monicakumari** [comment]
I am using google chrome latest version. 
could you please help me with AutoFirma ? How to use it and from where I can install it ?

**Comment by angelborroy-ks** [comment]
Then you need AutoFirma, from Chrome is required.

You can read project README, AutoFirma installer is linked there.

**Comment by monicakumari** [comment]
yes. I have checked 
[http://forja-ctt.administracionelectronica.gob.es/web/clienteafirma](url)

but not able to understand, from where it can be installed. 
please guide me a little.

thank you.

**Comment by angelborroy-ks** [comment]
Directly from README:

## esign-cert features
AutoFirma local application for computers is currently supported only for Windows, Mac OS and Linux. Available at [AutoFirma](http://firmaelectronica.gob.es/Home/Descargas.html)

**Comment by mikelasla** [comment]
sorry, i did not pretend  to close it, just pressed the wrong button

**Comment by monicakumari** [comment]
Thank you so much for help and quick reply.
I installed the AutoFirma. now I am getting some error message popup.. and no exception at console.
![screenshot from 2018-01-11 16-07-01](https://user-images.githubusercontent.com/26789477/34821501-f5780c48-f6e9-11e7-8d67-3e8e6985aeac.png)

**Comment by angelborroy-ks** [comment]
You need a personal electronic certificate to sign with.

**Comment by monicakumari** [comment]
I have created a test certificate using  "keytool -genkey -alias {desired alias certificate} -keystore {path to keystore.pfx} -storepass {password} -validity 365 -keyalg RSA -keysize 2048 -storetype pkcs12" command. and having a .png image of signature. 
but I dont know, how to use it. 
there is a jar  miniapplet-full_1_4.jar already provided in this add-on, so I thought samples will be there inside it. 
I got to know that I have to sign a jar using jarsigner but dont know how to create a jar first with the electronic certificate and signature.
kindly guide me, how do I create my own jar and after that I'll sign it using jarsigner. 

thank you.

**Comment by angelborroy-ks** [comment]
You don't need to sign JAR file, as it's already signed and it's not used to sign by using AutoFirma.

You need a personal certificate to sign when using AutoFirma.

**Comment by monicakumari** [comment]
ohh okay... I have a .pfx file, Do I need to put it somewhere in the installation ?

**Comment by monicakumari** [comment]
Can I have AutoFirma in english ?

**Comment by angelborroy-ks** [comment]
I don't know if AutoFirma is available in English. Likely it is not.

**Comment by monicakumari** [comment]
I am getting this, when saving a certificate with AutoFirma. 

![screenshot from 2018-01-11 17-04-32](https://user-images.githubusercontent.com/26789477/34823715-a2b79d40-f6f1-11e7-8e83-31a0030da92b.png)
