### ISSUE TITLE
Problemas con sign-frame.jsp

### ISSUE THREAD

**Issue by pgonzalez-git** [keensoft/alfresco-esign-cert#45]
Nos hemos encontrado con el caso que en un cliente que en la respuesta de /share/sign/sign-frame.jsp?... a la hora de montar esta url <%=request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + request.getContextPath()%> en vez generarla correctamente con las cabeceras de la request, que es como debería hacerlo, monta la url con distinto protocolo,cogiendo el nombre del servidor y con otro puerto.  
Ejemplo: https://docs.midominio.es/share/sign --> http://nombremáquina.midominio.es:8080/share/sign

¿Tenéis idea de saber qué sucede? Esta máquina tiene un apache por encima que  no controlamos nosotros, pero eso no debería ser el detonador dado que la request es correcta.

A no ser que le encuentre solución al por qué de ese comportamiento, me pregunto si podríamos cambiar la línea 4 y la 10
```
4 --> <script type="text/javascript" src="<%=request.getContextPath()%>/sign/miniapplet.js"></script>
</head>

10 --> MiniApplet.cargarMiniApplet('<%=request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + request.getContextPath()%>/sign');
```
Por lo siguiente
```
Usar ruta relativa aquí
4 --> <script type="text/javascript" src="<%=request.getContextPath()%>/sign/miniapplet.js"></script>

Y aquí cambiar la forma de montar la url
10 -->
     var url = window.location.protocol+'//'+window.location.hostname+(window.location.port ? ':'+window.location.port: '');
     MiniApplet.cargarMiniApplet(url+'/sign');
```

Gracias de antemano
Un saludo,

**Comment by mikelasla** [comment]
Buenas, 

Debería funcionar configurando el proxy en el conector, por ejemplo si usas AJP sería algo así

`<Connector port="8009" protocol="AJP/1.3" redirectPort="443" proxyName="docs.midominio.es" proxyPort="443" secure="true" scheme="https" />`


Saludos

**Comment by pgonzalez-git** [comment]
Buenas,

Gracias por la respuesta,

En otros entornos no hemos tenido que añadir el atributo 'proxyName' y funciona sin problemas. No obstante, lo probaremos. Vamos a solicitarle al cliente a ver que configuración ha puesto en el proxy...

Ya os comentaré cómo ha ido ;)
Un saludo,

**Comment by pgonzalez-git** [comment]
Hola!

Solucionado! El cliente tiene otro apache por encima, que en principio sólo redirigía, pero tras insistir que tenía que haber algo más, al final localizó él donde se había dejado algo por configurar... 

Gracias,
Un saludo,
